# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_AplicacionesComerciales_development

 
test:
  <<: *default
  database: project_AplicacionesComerciales_test


production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: project_AplicacionesComerciales_production
  username: project_AplicacionesComerciales
  password: <%= ENV["RAILWAYAPP_DATABASE_PASSWORD"] %>
